import "./globals.css";

import type { Metadata } from "next";
import { Oswald } from "next/font/google";

import MainHeader from "@/components/MainHeader";

const oswald = Oswald({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} antialiased`}>
        <div className="relative grid min-h-screen grid-rows-[6rem_1fr_20px] items-center justify-items-center bg-gradient-to-b from-grey-900 to-grey-800">
          <MainHeader />
          <main className="w-full px-4 pb-6 md:px-6">{children}</main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
